name: Visibility Detector Package

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches:
      - master
      - main

jobs:
  correctness:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/vector_graphics
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: master
      - run: flutter --version
      - run: flutter pub get
      - run: flutter format --set-exit-if-changed .
      - run: flutter analyze .
      - run: flutter test --coverage
