os: linux
before_script:
  - git clone https://github.com/flutter/flutter.git --depth 1
  - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
  - flutter doctor
script: ./tool/travis.sh
