analyzer:
  errors:
    # treat missing required parameters as a warning (not a hint)
    missing_required_param: warning
    # Allow having TODOs in the code
    todo: ignore
    # TODO(jamesderlin): Temporarily disable unnecessary null comparisons during
    # the transition to null-safety.
    unnecessary_null_comparison: ignore

linter:
  rules:
    # these rules are documented on and in the same order as
    # the Dart Lint rules page to make maintenance easier
    # https://github.com/dart-lang/linter/blob/master/example/all.yaml
    - always_declare_return_types
    - annotate_overrides
    # TODO - avoid_as
    - avoid_empty_else
    - avoid_init_to_null
    - avoid_return_types_on_setters
    - await_only_futures
    - camel_case_types
    - cancel_subscriptions
    - close_sinks
    #- comment_references # TODO
    - constant_identifier_names
    - control_flow_in_finally
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - hash_and_equals
    - implementation_imports
    - invariant_booleans
    - iterable_contains_unrelated_type
    - library_names
    - library_prefixes
    - list_remove_unrelated_type
    #- literal_only_boolean_expressions # https://github.com/dart-lang/linter/issues/453
    - non_constant_identifier_names
    - one_member_abstracts
    - only_throw_errors
    - overridden_fields
    - package_api_docs
    - package_names
    - package_prefixed_library_names
    - prefer_is_not_empty
    - slash_for_doc_comments
    #- sort_constructors_first
    - sort_unnamed_constructors_first
    - test_types_in_equals
    - throw_in_finally
    #- type_annotate_public_apis # Annoying for cases with obvious types.
    - type_init_formals
    - unawaited_futures
    - unnecessary_getters_setters
    - unnecessary_new
    - unrelated_type_equality_checks
    - valid_regexps
