name: flutter_widgets
version: 0.1.7
description: >
  Flutter widgets that are developed by Google but not by the core
  Flutter team.
homepage: https://github.com/google/flutter.widgets

environment:
  sdk: ">=2.3.0 <3.0.0"
  flutter: ^1.9.1

dependencies:
  collection: ^1.14.5
  flutter:
    sdk: flutter
  html: ^0.14.0
  meta: ^1.1.1
  quiver: ^2.0.0+1

dev_dependencies:
  test: ^1.3.0
  mockito: ^3.0.0
  pedantic: ^1.8.0
  flutter_test:
    sdk: flutter
