name: scrollable_positioned_list_example

publish_to: "none"

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=2.12.0"

dependencies:
  flutter:
    sdk: flutter
  scrollable_positioned_list:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.1
