name: self_storing_input_demo

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.11
  # Currently the example references self_storing_input by relative path.
  # If you copy the example to other place, you need to either update the path
  # or reference pub.dev:
  #
  # self_storing_input: <latest version>
  #
  # Find the latest version here: https://pub.dev/packages/self_storing_input
  self_storing_input:
    path: ..

flutter:
  uses-material-design: true
